pipeline {
    agent any

    tools {
        maven 'MAVEN_3_6_3'
        jdk 'JDK_17'
    }

    stages {
        stage('Checkout') {
            steps {
                // Asumiendo que el código fuente se clona en el directorio correcto
                checkout scm
            }
        }

        stage('Unit Test') {
            steps {
                // Cambiar al directorio donde está el pom.xml antes de ejecutar Maven
                dir('D:/UNIVERSIDAD/7MO_SEMESTRE/Disenio_de_experimentos/TRABAJO DOCKSEEKER/Backend/docseeker') {
                    bat 'mvn clean test -Dtest=ReservationServiceImplTest'
                }
            }
            post {
                always {
                    // Asumiendo que estás en el directorio correcto y los informes se generan allí
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
