pipeline {
    agent any

    tools {
        maven 'MAVEN_3_6_3'
        jdk 'JDK_17'
    }

    stages {
        stage('Checkout') {
            steps {

                checkout scm
            }
        }

        stage('Unit Test') {
            steps {
                // Cambiar al directorio donde está el pom.xml antes de ejecutar Maven
                dir('D:/UNIVERSIDAD/7MO_SEMESTRE/Disenio_de_experimentos/TRABAJO DOCKSEEKER/Backend') {
                    bat 'mvn clean test'
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
